apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./blog-infra-k8s/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: larturi/blog-client
      context: blog-client-react
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    - image: larturi/comments
      context: blog-service-comments-node
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: larturi/eventbus
      context: blog-event-bus-node
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: larturi/moderation
      context: blog-service-moderation-node
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: larturi/posts
      context: blog-service-posts-node
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: larturi/query
      context: blog-service-query-node
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
