apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-eventbus-service-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventbus
  template:
    metadata:
      labels:
        app: eventbus
    spec:
      containers:
        - name: eventbus
          image: larturi/eventbus:latest
---
apiVersion: v1
kind: Service
metadata:
  name: eventbus-srv
spec:
  selector:
    app: eventbus
  type: ClusterIP
  ports:
    - name: eventbus
      protocol: TCP
      port: 8000
      targetPort: 8000

