apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-moderation-service-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation
  template:
    metadata:
      labels:
        app: moderation
    spec:
      containers:
        - name: moderation
          image: larturi/moderation:latest
