apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-posts-service-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: larturi/posts:latest
---
apiVersion: v1
kind: Service
metadata:
  name: posts-srv-cluster-ip
spec:
  selector:
    app: posts
  type: ClusterIP
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000