apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-query-service-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: query
  template:
    metadata:
      labels:
        app: query
    spec:
      containers:
        - name: query
          image: larturi/query:latest
